import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface Language {
  code: string;
  name: string;
  flag: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const languages: Language[] = [
  { code: 'pt', name: 'Português', flag: 'https://flagcdn.com/br.svg' },
  { code: 'en', name: 'English', flag: 'https://flagcdn.com/gb.svg' },
  { code: 'es', name: 'Español', flag: 'https://flagcdn.com/es.svg' },
  { code: 'fr', name: 'Français', flag: 'https://flagcdn.com/fr.svg' },
  { code: 'de', name: 'Deutsch', flag: 'https://flagcdn.com/de.svg' },
  { code: 'it', name: 'Italiano', flag: 'https://flagcdn.com/it.svg' },
  { code: 'ru', name: 'Русский', flag: 'https://flagcdn.com/ru.svg' },
  { code: 'ar', name: 'العربية', flag: 'https://flagcdn.com/sa.svg' } // Removido dir: 'rtl'
];

const translations = {
  pt: {
    welcome: 'Bem-vindo ao Observatório UFNT',
    greeting: 'Olá, {{name}}! Bem-vindo ao nosso sistema',
    repository: 'REPOSITÓRIO',
    team: 'EQUIPE',
    research: 'PESQUISA',
    news: 'NOTÍCIAS',
    lectures: 'PALESTRAS',
    login: 'ENTRAR',
    verify_facts: 'Verifique os fatos',
    observatory_name: 'Observatório Norte',
    observatory_logo_alt: 'Logo do Observatório',
    mission_title: 'Combate à Desinformação e Fake News com Pesquisa e Educação',
    mission_text: 'No mundo digital de hoje, a disseminação de fake news tornou-se um desafio global.',
    latest_research: 'Últimas Pesquisas',
    fake_news_examples: 'Exemplos Educacionais de Fake News',
    fake_news_description: 'Conheça exemplos fictícios de fake news para aprender a identificar informações falsas.',
    how_to_identify: 'Como Identificar Fake News',
    partners: 'Parceiros',
    photo_gallery: 'Galeria de Fotos',
    quick_links: 'Links Rápidos',
    resources: 'Recursos',
    newsletter: 'Newsletter',
    copyright: '© {{year}} Observatório Norte. Todos os direitos reservados.',
    community_observatory: 'Comunidade Observatório',
    your_email: 'Seu e-mail',
    subscribe: 'Inscrever',
    about: 'Sobre',
    publications: 'Publicações',
    contact: 'Contato',
    knowledge_base: 'Base de Conhecimento',
    tools: 'Ferramentas',
    api: 'API',
    faq: 'FAQ',
    read_more: 'Ler mais',
    analysis: 'Análise',
    shares: 'compartilhamentos',
    fake_news_label: 'EXEMPLO DE FAKE NEWS',
    science_category: 'Ciência',
    technology_category: 'Tecnologia',
    health_category: 'Saúde',
    education_category: 'Educação',
    research_category: 'Pesquisa',
    alert_category: 'ALERTA',
    previous_slide: 'Slide anterior',
    next_slide: 'Próximo slide',
    go_to_slide: 'Ir para slide',
    mobile_menu_aria: 'Menu mobile',
    example_1_title: 'Dragões Descobertos na Amazônia',
    example_1_content: 'Notícia falsa sobre suposta descoberta de dragões na floresta amazônica.',
    example_2_title: 'Celulares Que Leem Pensamentos',
    example_2_content: 'Exemplo fictício de como a tecnologia pode ser distorcida em notícias falsas.',
    example_3_title: 'Pizza Concede Imortalidade',
    example_3_content: 'Exemplo absurdo de como fake news podem distorcer informações sobre saúde.',
    tip_1_title: 'Verifique a Fonte',
    tip_1_description: 'Sempre confira se a notícia vem de um veículo jornalístico reconhecido.',
    tip_2_title: 'Cuidado com Títulos Sensacionalistas',
    tip_2_description: 'Títulos exagerados ou muito emocionais são um sinal de alerta.',
    tip_3_title: 'Consulte Outras Fontes',
    tip_3_description: 'Veja se outros veículos confiáveis estão reportando o mesmo fato.',
    tip_4_title: 'Use o Pensamento Crítico',
    tip_4_description: 'Questione se a informação faz sentido e se há provas concretas.',
    slide_1_title: 'Montanhas Místicas',
    slide_2_title: 'Sonhos Urbanos',
    slide_3_title: 'Noites de Néon',
    slide_4_title: 'Sussurros do Deserto',
    explore_button: 'Explorar Componente',
    footer_description: 'Promovendo a verdade e combatendo a desinformação.',
    mission_image_alt: 'Imagem ilustrativa da missão'
  },
  en: {
    welcome: 'Welcome to UFNT Observatory',
    greeting: 'Hello, {{name}}! Welcome to our system',
    repository: 'REPOSITORY',
    team: 'TEAM',
    research: 'RESEARCH',
    news: 'NEWS',
    lectures: 'LECTURES',
    login: 'LOGIN',
    verify_facts: 'Verify facts',
    observatory_name: 'North Observatory',
    observatory_logo_alt: 'Observatory Logo',
    mission_title: 'Combating Disinformation and Fake News with Research and Education',
    mission_text: "In today's digital world, the spread of fake news has become a global challenge.",
    latest_research: 'Latest Research',
    fake_news_examples: 'Educational Examples of Fake News',
    fake_news_description: 'Learn about fictional examples of fake news to identify false information.',
    how_to_identify: 'How to Identify Fake News',
    partners: 'Partners',
    photo_gallery: 'Photo Gallery',
    quick_links: 'Quick Links',
    resources: 'Resources',
    newsletter: 'Newsletter',
    copyright: '© {{year}} North Observatory. All rights reserved.',
    community_observatory: 'Observatory Community',
    your_email: 'Your email',
    subscribe: 'Subscribe',
    about: 'About',
    publications: 'Publications',
    contact: 'Contact',
    knowledge_base: 'Knowledge Base',
    tools: 'Tools',
    api: 'API',
    faq: 'FAQ',
    read_more: 'Read more',
    analysis: 'Analysis',
    shares: 'shares',
    fake_news_label: 'FAKE NEWS EXAMPLE',
    science_category: 'Science',
    technology_category: 'Technology',
    health_category: 'Health',
    education_category: 'Education',
    research_category: 'Research',
    alert_category: 'ALERT',
    previous_slide: 'Previous slide',
    next_slide: 'Next slide',
    go_to_slide: 'Go to slide',
    mobile_menu_aria: 'Mobile menu',
    example_1_title: 'Dragons Discovered in the Amazon',
    example_1_content: 'Fake news about alleged discovery of dragons in the Amazon rainforest.',
    example_2_title: 'Phones That Read Thoughts',
    example_2_content: 'Fictional example of how technology can be distorted in fake news.',
    example_3_title: 'Pizza Grants Immortality',
    example_3_content: 'Absurd example of how fake news can distort health information.',
    tip_1_title: 'Check the Source',
    tip_1_description: 'Always verify if the news comes from a recognized journalistic source.',
    tip_2_title: 'Beware of Sensationalist Headlines',
    tip_2_description: 'Exaggerated or overly emotional headlines are a warning sign.',
    tip_3_title: 'Consult Other Sources',
    tip_3_description: 'See if other reliable media are reporting the same fact.',
    tip_4_title: 'Use Critical Thinking',
    tip_4_description: 'Question whether the information makes sense and if there is concrete evidence.',
    slide_1_title: 'Mystic Mountains',
    slide_2_title: 'Urban Dreams',
    slide_3_title: 'Neon Nights',
    slide_4_title: 'Desert Whispers',
    explore_button: 'Explore Component',
    footer_description: 'Promoting truth and combating disinformation.',
    mission_image_alt: 'Mission illustration image'
  },
  ar: {
    welcome: "مرحبًا بكم في مرصد UFNT",
    greeting: "مرحبًا {{name}}! أهلاً بكم في نظامنا",
    repository: "المستودع",
    team: "الفريق",
    research: "البحث",
    news: "الأخبار",
    lectures: "المحاضرات",
    login: "تسجيل الدخول",
    verify_facts: "تحقق من الحقائق",
    observatory_name: "المرصد الشمالي",
    observatory_logo_alt: "شعار المرصد",
    mission_title: "مكافحة التضليل والأخبار المزيفة بالبحث والتعليم",
    mission_text: "في العالم الرقمي اليوم، أصبح انتشار الأخبار المزيفة تحديًا عالميًا.",
    latest_research: "أحدث الأبحاث",
    fake_news_examples: "أمثلة تعليمية للأخبار المزيفة",
    fake_news_description: "تعرف على أمثلة افتراضية للأخبار المزيفة لتعلم كيفية تحديد المعلومات الخاطئة.",
    how_to_identify: "كيفية تحديد الأخبار المزيفة",
    partners: "الشركاء",
    photo_gallery: "معرض الصور",
    quick_links: "روابط سريعة",
    resources: "الموارد",
    newsletter: "النشرة الإخبارية",
    copyright: "© {{year}} المرصد الشمالي. جميع الحقوق محفوظة.",
    community_observatory: "مجتمع المرصد",
    your_email: "بريدك الإلكتروني",
    subscribe: "اشتراك",
    about: "حول",
    publications: "المنشورات",
    contact: "اتصل بنا",
    knowledge_base: "قاعدة المعرفة",
    tools: "الأدوات",
    api: "واجهة برمجة التطبيقات",
    faq: "الأسئلة الشائعة",
    read_more: "اقرأ المزيد",
    analysis: "تحليل",
    shares: "مشاركات",
    fake_news_label: "مثال على أخبار مزيفة",
    science_category: "العلوم",
    technology_category: "التكنولوجيا",
    health_category: "الصحة",
    education_category: "التعليم",
    research_category: "البحث",
    alert_category: "تنبيه",
    previous_slide: "الشريحة السابقة",
    next_slide: "الشريحة التالية",
    go_to_slide: "انتقل إلى الشريحة",
    mobile_menu_aria: "قائمة الجوال",
    example_1_title: "اكتشاف تنانين في الأمازون",
    example_1_content: "خبر زائف عن اكتشاف مزعوم للتنانين في غابة الأمازون.",
    example_2_title: "هواتف تقرأ الأفكار",
    example_2_content: "مثال افتراضي عن كيف يمكن تشويه التكنولوجيا في الأخبار المزيفة.",
    example_3_title: "البيتزا تمنح الخلود",
    example_3_content: "مثال سخيف عن كيف يمكن تشويه المعلومات حول الغذاء والصحة.",
    tip_1_title: "تحقق من المصدر",
    tip_1_description: "تأكد دائمًا من أن الخبر يأتي من مصدر إخباري موثوق.",
    tip_2_title: "احذر من العناوين المثيرة",
    tip_2_description: "العناوين المبالغ فيها أو العاطفية هي علامة تحذير.",
    tip_3_title: "استشر مصادر أخرى",
    tip_3_description: "تحقق مما إذا كانت وسائل إعلام أخرى موثوقة تذكر نفس الحقيقة.",
    tip_4_title: "استخدم التفكير النقدي",
    tip_4_description: "اسأل نفسك إذا كانت المعلومات منطقية وهناك أدلة ملموسة.",
    slide_1_title: "جبال غامضة",
    slide_2_title: "أحلام حضرية",
    slide_3_title: "ليالي نيون",
    slide_4_title: "همسات الصحراء",
    explore_button: "استكشف المكون",
    footer_description: "تعزيز الحقيقة ومكافحة التضليل.",
    mission_image_alt: "صورة توضيحية للمهمة"
  },
  fr: {
    welcome: "Bienvenue à l'Observatoire UFNT",
    greeting: "Bonjour {{name}}! Bienvenue dans notre système",
    repository: "RÉFÉRENTIEL",
    team: "ÉQUIPE",
    research: "RECHERCHE",
    news: "ACTUALITÉS",
    lectures: "CONFÉRENCES",
    login: "CONNEXION",
    verify_facts: "Vérifier les faits",
    observatory_name: "Observatoire Nord",
    observatory_logo_alt: "Logo de l'Observatoire",
    mission_title: "Lutter contre la désinformation et les fausses nouvelles par la recherche et l'éducation",
    mission_text: "Dans le monde numérique d'aujourd'hui, la propagation des fausses nouvelles est devenue un défi mondial.",
    latest_research: "Dernières recherches",
    fake_news_examples: "Exemples éducatifs de fausses nouvelles",
    fake_news_description: "Découvrez des exemples fictifs de fausses nouvelles pour apprendre à identifier les fausses informations.",
    how_to_identify: "Comment identifier les fausses nouvelles",
    partners: "Partenaires",
    photo_gallery: "Galerie photo",
    quick_links: "Liens rapides",
    resources: "Ressources",
    newsletter: "Newsletter",
    copyright: "© {{year}} Observatoire Nord. Tous droits réservés.",
    community_observatory: "Communauté de l'Observatoire",
    your_email: "Votre email",
    subscribe: "S'abonner",
    about: "À propos",
    publications: "Publications",
    contact: "Contact",
    knowledge_base: "Base de connaissances",
    tools: "Outils",
    api: "API",
    faq: "FAQ",
    read_more: "Lire plus",
    analysis: "Analyse",
    shares: "partages",
    fake_news_label: "EXEMPLE DE FAUSSE NOUVELLE",
    science_category: "Science",
    technology_category: "Technologie",
    health_category: "Santé",
    education_category: "Éducation",
    research_category: "Recherche",
    alert_category: "ALERTE",
    previous_slide: "Diapositive précédente",
    next_slide: "Diapositive suivante",
    go_to_slide: "Aller à la diapositive",
    mobile_menu_aria: "Menu mobile",
    example_1_title: "Dragons découverts en Amazonie",
    example_1_content: "Fausse nouvelle sur la prétendue découverte de dragons dans la forêt amazonienne.",
    example_2_title: "Téléphones qui lisent les pensées",
    example_2_content: "Exemple fictif de distorsion technologique dans les fausses nouvelles.",
    example_3_title: "La pizza confère l'immortalité",
    example_3_content: "Exemple absurde de distorsion d'informations sur la santé.",
    tip_1_title: "Vérifiez la source",
    tip_1_description: "Vérifiez toujours si la nouvelle provient d'une source journalistique reconnue.",
    tip_2_title: "Méfiez-vous des titres sensationnalistes",
    tip_2_description: "Les titres exagérés ou trop émotionnels sont un signe d'alerte.",
    tip_3_title: "Consultez d'autres sources",
    tip_3_description: "Voyez si d'autres médias fiables rapportent le même fait.",
    tip_4_title: "Utilisez l'esprit critique",
    tip_4_description: "Demandez-vous si l'information est logique et s'il y a des preuves concrètes.",
    slide_1_title: "Montagnes mystiques",
    slide_2_title: "Rêves urbains",
    slide_3_title: "Nuits néon",
    slide_4_title: "Chuchotements du désert",
    explore_button: "Explorer le composant",
    footer_description: "Promouvoir la vérité et lutter contre la désinformation.",
    mission_image_alt: "Image illustrative de la mission"
  },
  de: {
    welcome: "Willkommen beim UFNT Observatorium",
    greeting: "Hallo {{name}}! Willkommen in unserem System",
    repository: "REPOSITORIUM",
    team: "TEAM",
    research: "FORSCHUNG",
    news: "NACHRICHTEN",
    lectures: "VORTRÄGE",
    login: "ANMELDUNG",
    verify_facts: "Fakten überprüfen",
    observatory_name: "Nord Observatorium",
    observatory_logo_alt: "Observatorium Logo",
    mission_title: "Bekämpfung von Desinformation und Fake News durch Forschung und Bildung",
    mission_text: "In der heutigen digitalen Welt ist die Verbreitung von Fake News zu einer globalen Herausforderung geworden.",
    latest_research: "Neueste Forschung",
    fake_news_examples: "Lehrreiche Beispiele für Fake News",
    fake_news_description: "Lernen Sie anhand fiktiver Beispiele, Falschinformationen zu erkennen.",
    how_to_identify: "Wie man Fake News erkennt",
    partners: "Partner",
    photo_gallery: "Fotogalerie",
    quick_links: "Schnellzugriff",
    resources: "Ressourcen",
    newsletter: "Newsletter",
    copyright: "© {{year}} Nord Observatorium. Alle Rechte vorbehalten.",
    community_observatory: "Observatorium Gemeinschaft",
    your_email: "Ihre E-Mail",
    subscribe: "Abonnieren",
    about: "Über uns",
    publications: "Publikationen",
    contact: "Kontakt",
    knowledge_base: "Wissensdatenbank",
    tools: "Werkzeuge",
    api: "API",
    faq: "FAQ",
    read_more: "Weiterlesen",
    analysis: "Analyse",
    shares: "Aktien",
    fake_news_label: "BEISPIEL FÜR FAKE NEWS",
    science_category: "Wissenschaft",
    technology_category: "Technologie",
    health_category: "Gesundheit",
    education_category: "Bildung",
    research_category: "Forschung",
    alert_category: "ALARM",
    previous_slide: "Vorherige Folie",
    next_slide: "Nächste Folie",
    go_to_slide: "Zur Folie gehen",
    mobile_menu_aria: "Mobiles Menü",
    example_1_title: "Drachen im Amazonas entdeckt",
    example_1_content: "Falschmeldung über angebliche Drachen im Amazonas-Regenwald.",
    example_2_title: "Handys, die Gedanken lesen",
    example_2_content: "Fiktives Beispiel für technologische Verzerrung in Fake News.",
    example_3_title: "Pizza verleiht Unsterblichkeit",
    example_3_content: "Absurdes Beispiel für Gesundheitsdesinformation.",
    tip_1_title: "Quelle überprüfen",
    tip_1_description: "Prüfen Sie immer, ob die Nachricht von einer seriösen Quelle stammt.",
    tip_2_title: "Vorsicht bei reißerischen Überschriften",
    tip_2_description: "Übertriebene oder emotionalisierte Überschriften sind Warnsignale.",
    tip_3_title: "Andere Quellen konsultieren",
    tip_3_description: "Prüfen Sie, ob andere seriöse Medien denselben Sachverhalt melden.",
    tip_4_title: "Kritisches Denken anwenden",
    tip_4_description: "Hinterfragen Sie, ob die Information plausibel ist und es Beweise gibt.",
    slide_1_title: "Mystische Berge",
    slide_2_title: "Urbane Träume",
    slide_3_title: "Neon-Nächte",
    slide_4_title: "Wüstenflüstern",
    explore_button: "Komponente erkunden",
    footer_description: "Wahrheit fördern und Desinformation bekämpfen.",
    mission_image_alt: "Illustration der Mission"
  },
  it: {
    welcome: "Benvenuti all'Osservatorio UFNT",
    greeting: "Ciao {{name}}! Benvenuto nel nostro sistema",
    repository: "REPOSITORY",
    team: "TEAM",
    research: "RICERCA",
    news: "NOTIZIE",
    lectures: "CONFERENZE",
    login: "ACCEDI",
    verify_facts: "Verifica i fatti",
    observatory_name: "Osservatorio Nord",
    observatory_logo_alt: "Logo dell'Osservatorio",
    mission_title: "Combattere la disinformazione e le fake news con ricerca ed educazione",
    mission_text: "Nel mondo digitale di oggi, la diffusione di fake news è diventata una sfida globale.",
    latest_research: "Ultime ricerche",
    fake_news_examples: "Esempi educativi di fake news",
    fake_news_description: "Scopri esempi fittizi di fake news per imparare a identificare le informazioni false.",
    how_to_identify: "Come identificare le fake news",
    partners: "Partner",
    photo_gallery: "Galleria fotografica",
    quick_links: "Link rapidi",
    resources: "Risorse",
    newsletter: "Newsletter",
    copyright: "© {{year}} Osservatorio Nord. Tutti i diritti riservati.",
    community_observatory: "Comunità dell'Osservatorio",
    your_email: "La tua email",
    subscribe: "Iscriviti",
    about: "Chi siamo",
    publications: "Pubblicazioni",
    contact: "Contatti",
    knowledge_base: "Base di conoscenza",
    tools: "Strumenti",
    api: "API",
    faq: "FAQ",
    read_more: "Leggi di più",
    analysis: "Analisi",
    shares: "condivisioni",
    fake_news_label: "ESEMPIO DI FAKE NEWS",
    science_category: "Scienza",
    technology_category: "Tecnologia",
    health_category: "Salute",
    education_category: "Educazione",
    research_category: "Ricerca",
    alert_category: "ALLERTA",
    previous_slide: "Slide precedente",
    next_slide: "Slide successiva",
    go_to_slide: "Vai alla slide",
    mobile_menu_aria: "Menu mobile",
    example_1_title: "Draghi scoperti in Amazzonia",
    example_1_content: "Fake news sulla presunta scoperta di draghi nella foresta amazzonica.",
    example_2_title: "Telefoni che leggono la mente",
    example_2_content: "Esempio fittizio di distorsione tecnologica nelle fake news.",
    example_3_title: "La pizza dona l'immortalità",
    example_3_content: "Esempio assurdo di disinformazione sulla salute.",
    tip_1_title: "Verifica la fonte",
    tip_1_description: "Controlla sempre se la notizia proviene da una fonte giornalistica riconosciuta.",
    tip_2_title: "Diffida dei titoli sensazionalistici",
    tip_2_description: "Titoli esagerati o troppo emotivi sono un segnale d'allarme.",
    tip_3_title: "Consulta altre fonti",
    tip_3_description: "Verifica se altri media affidabili riportano lo stesso fatto.",
    tip_4_title: "Usa il pensiero critico",
    tip_4_description: "Chiediti se l'informazione ha senso e se ci sono prove concrete.",
    slide_1_title: "Montagne mistiche",
    slide_2_title: "Sogni urbani",
    slide_3_title: "Notti al neon",
    slide_4_title: "Sussurri del deserto",
    explore_button: "Esplora il componente",
    footer_description: "Promuovere la verità e combattere la disinformazione.",
    mission_image_alt: "Immagine illustrativa della missione"
  },
  ru: {
    welcome: "Добро пожаловать в обсерваторию UFNT",
    greeting: "Привет, {{name}}! Добро пожаловать в нашу систему",
    repository: "РЕПОЗИТОРИЙ",
    team: "КОМАНДА",
    research: "ИССЛЕДОВАНИЯ",
    news: "НОВОСТИ",
    lectures: "ЛЕКЦИИ",
    login: "ВОЙТИ",
    verify_facts: "Проверить факты",
    observatory_name: "Северная обсерватория",
    observatory_logo_alt: "Логотип обсерватории",
    mission_title: "Борьба с дезинформацией и фейковыми новостями с помощью исследований и образования",
    mission_text: "В современном цифровом мире распространение фейковых новостей стало глобальной проблемой.",
    latest_research: "Последние исследования",
    fake_news_examples: "Образовательные примеры фейковых новостей",
    fake_news_description: "Изучите вымышленные примеры фейковых новостей, чтобы научиться выявлять ложную информацию.",
    how_to_identify: "Как распознать фейковые новости",
    partners: "Партнеры",
    photo_gallery: "Фотогалерея",
    quick_links: "Быстрые ссылки",
    resources: "Ресурсы",
    newsletter: "Рассылка",
    copyright: "© {{year}} Северная обсерватория. Все права защищены.",
    community_observatory: "Сообщество обсерватории",
    your_email: "Ваш email",
    subscribe: "Подписаться",
    about: "О нас",
    publications: "Публикации",
    contact: "Контакты",
    knowledge_base: "База знаний",
    tools: "Инструменты",
    api: "API",
    faq: "FAQ",
    read_more: "Читать далее",
    analysis: "Анализ",
    shares: "акции",
    fake_news_label: "ПРИМЕР ФЕЙКОВЫХ НОВОСТЕЙ",
    science_category: "Наука",
    technology_category: "Технологии",
    health_category: "Здоровье",
    education_category: "Образование",
    research_category: "Исследования",
    alert_category: "ТРЕВОГА",
    previous_slide: "Предыдущий слайд",
    next_slide: "Следующий слайд",
    go_to_slide: "Перейти к слайду",
    mobile_menu_aria: "Мобильное меню",
    example_1_title: "Драконы обнаружены в Амазонии",
    example_1_content: "Фейковая новость о якобы обнаруженных драконах в амазонских джунглях.",
    example_2_title: "Телефоны, читающие мысли",
    example_2_content: "Вымышленный пример искажения технологий в фейковых новостях.",
    example_3_title: "Пицца дарует бессмертие",
    example_3_content: "Абсурдный пример дезинформации о здоровье.",
    tip_1_title: "Проверьте источник",
    tip_1_description: "Всегда проверяйте, приходит ли новость из признанного журналистского источника.",
    tip_2_title: "Остерегайтесь сенсационных заголовков",
    tip_2_description: "Преувеличенные или слишком эмоциональные заголовки — это предупредительный знак.",
    tip_3_title: "Проконсультируйтесь с другими источниками",
    tip_3_description: "Посмотрите, сообщают ли другие надежные СМИ о том же факте.",
    tip_4_title: "Используйте критическое мышление",
    tip_4_description: "Спросите себя, имеет ли информация смысл и есть ли конкретные доказательства.",
    slide_1_title: "Мистические горы",
    slide_2_title: "Городские мечты",
    slide_3_title: "Неоновые ночи",
    slide_4_title: "Шепот пустыни",
    explore_button: "Исследовать компонент",
    footer_description: "Продвижение правды и борьба с дезинформацией.",
    mission_image_alt: "Иллюстративное изображение миссии"
  }
  
  
};

export const LanguageProvider: React.FC<{children: ReactNode}> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLang = localStorage.getItem('selectedLanguage');
    return savedLang ? JSON.parse(savedLang) : languages[0];
  });

  useEffect(() => {
    localStorage.setItem('selectedLanguage', JSON.stringify(language));
    document.documentElement.lang = language.code;
    document.documentElement.dir = 'ltr'; // Forçando direção LTR para todo o documento
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language.code]?.[key] || key;
    
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{{${param}}}`, String(value));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};